#!/bin/bash

function help {
	case "$1" in
		1)
			;;
		2)
			echo "Muestra todos los plugins configurados."
			;;
	esac
}

function call {
	if [ "$1" == "help" ]; then
		help 2
		exit 0
	fi

	for path in ${PLUGIN_PATH}; do
		expanded_path=$(bash -c "echo $path")
		pushd "$expanded_path" 2> /dev/null > /dev/null
		if [ $? = 0 ]; then
			for i in hpqc-*; do
				if [ "$i" != 'hpqc-*' ]; then
					echo ${i/hpqc-/}
				fi
			done
			popd > /dev/null
		fi
	done
}
