#!/bin/bash
function help {
	case $1 in
		1)
			;;
		2)
			echo "Crea una cache local de los metadatos de HPQC."
			;;
	esac
}

function call {
	if [ "$1" == "help" ]; then
		man hpqc-build-cache
		exit 0
	fi

	[ ! -e ${CACHE} ] && mkdir -p ${CACHE}
	[ ! -d ${CACHE} ] && echo "${CACHE} no es un directorio" && exit 1
	
	rm ${CACHE}/*
	# AUTHENTICATE
	doLogin
	
	# LIST OF ENTITIES
	sendGET "${BASE_URL}/qcbin/rest/domains/${DOMAIN}/projects/${PROJECT}/customization/entities" | xsltproc $(getFilter entities) - | sed -e '1d' > ${CACHE}/entities.csv
	
	# GETS THE FIELDS OF EACH ENTITIE
	while read line; do
		OLD_IFS=$IFS
		IFS='|'
		tokens=($line)
		IFS=${OLD_IFS}
	
		if [ -n "${tokens[0]}" ]; then
			ENTITIE=${CACHE}/entity_${tokens[0]}_fields.csv
			
			sendGET "${BASE_URL}/qcbin/rest/domains/${DOMAIN}/projects/${PROJECT}/customization/entities/${tokens[0]}/fields" | xsltproc $(getFilter entity) - | sed -e '1d' > ${ENTITIE}
		fi
	
		# GETS THE LISTS USED
		while read entitie_line; do
			OLD_IFS=$IFS
			IFS='|'
			entitie_tokens=($entitie_line)
			IFS=${OLD_IFS}
			if [ "${entitie_tokens[7]}" = "LookupList" ]; then
				LISTS="$LISTS ${entitie_tokens[15]}"
			fi
		done < ${ENTITIE}
	done < ${CACHE}/entities.csv
	
	UNIQ_LISTS="$(echo ${LISTS} | tr ' ' '\n' | sort -g | uniq)"
	for list in ${UNIQ_LISTS}; do
		LIST="${CACHE}/list_${list}.csv"
		sendGET "${BASE_URL}/qcbin/rest/domains/${DOMAIN}/projects/${PROJECT}/customization/lists?id=${list}" | xsltproc $(getFilter list) - | sed -e '1d' > ${LIST}
	
	done
	
	# GETS RELEASES
	sendGET "${BASE_URL}/qcbin/rest/domains/${DOMAIN}/projects/${PROJECT}/releases" | xsltproc $(getFilter releases) - | sed -e '1d' > ${CACHE}/releases.csv

	# GETS CYCLES
	sendGET "${BASE_URL}/qcbin/rest/domains/${DOMAIN}/projects/${PROJECT}/release-cycles?page-size=${MAX_DEFECTS}" | xsltproc $(getFilter release-cycles) - | sed -e '1d' > ${CACHE}/release-cycles.csv

	doLogout	
}
