#!/bin/bash


function help {
	case $1 in
		1)
			case "$2" in
				get | release | status | do-lock)
					cut -f1 -d'|' ~/.hpqc/cache/entities.csv | tr '\n' ' '
					;;
				*)
					echo "get release status do-locked"
					;;
			esac
			;;
		2)
			echo $"Locks an entity."
			;;
	esac
}

function call {
	if [ "$1" == "help" ]; then
		echo $"Locks an entity in HPQC to prevent it to be modified by other users. You can check the list of entities in ~/.hpqc/cache/entities.csv."
		echo $"Example:"
		echo
		echo $"hpqc lock get defect 21560"
		echo $"hpqc lock release defect 21560"
		echo $"hpqc lock status defect 21560"
		echo
		exit 0
	fi

	[ ! -d ${CACHE} ] && echo $"${CACHE} isn't a directory." && exit 1
	
	# AUTHENTICATE
	curl --basic -D ${HEAD} --cookie-jar ${COOKIES} -u "${USER}:${PASS}" "${BASE_URL}/qcbin/authentication-point/authenticate"

	case "$1" in
		get)
			MODE="POST"
			;;
		release)
			MODE="DELETE"
			;;
		status)
			MODE="GET"
			;;
		do-locked)
			MODE="DO-LOCKED"
			;;
		*)
			echo $"Error: you shuld put one mode: get, release or status."
			exit 1;
			;;
	esac

	shift

	ENTITY_TYPE="$1"
	ENTITY_ID="$2"
	shift 2

	[ -z "$ENTITY_TYPE" ] && echo $"There isn't an entity type." && exit 1
	[ -z "$ENTITY_ID"   ] && echo $"There isn't an entity id." && exit 1

	TMP_FILE=$(mktemp /tmp/defects.XXXXXXXXXX)

	if [ "$MODE" != "DO-LOCKED" ]; then
		curl -X "$MODE" -D ${HEAD} --cookie ${COOKIES} --cookie-jar ${COOKIES} -g "${BASE_URL}/qcbin/rest/domains/${DOMAIN}/projects/${PROJECT}/${ENTITY_TYPE}/${ENTITY_ID}/lock" > ${TMP_FILE}
	else
		curl -X "POST" -D ${HEAD} --cookie ${COOKIES} --cookie-jar ${COOKIES} -g "${BASE_URL}/qcbin/rest/domains/${DOMAIN}/projects/${PROJECT}/${ENTITY_TYPE}/${ENTITY_ID}/lock" > ${TMP_FILE}

		$@

		curl -X "DELETE" -D ${HEAD} --cookie ${COOKIES} --cookie-jar ${COOKIES} -g "${BASE_URL}/qcbin/rest/domains/${DOMAIN}/projects/${PROJECT}/${ENTITY_TYPE}/${ENTITY_ID}/lock" > ${TMP_FILE}
	fi
	
	cat "${TMP_FILE}"
	
	rm ${TMP_FILE}
	
	rm ${COOKIES}
}

